#!/usr/bin/env bash
# This script modifies the /etc/hosts file to change localhost IP

# Ensure the script is run as root
if [ "$(id -u)" -ne 0 ]; then
    echo "Please run as root"
    exit 1
fi 

# Backup the original /etc/hosts file
cp /etc/hosts /etc/hosts.backup

# Update the /etc/hosts file
sed -i '/127.0.0.1\s\+localhost/c\127.0.0.2 localhost' /etc/hosts
sed -i '/^#.*facebook.com/d' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts

echo "Hosts file updated successfully."
